# Generated by Django 5.2.7 on 2025-11-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('vehiculo', 'Renta de Vehículos'), ('apartamento', 'Renta de Apartamentos'), ('bote', 'Renta de Botes'), ('paquete', 'Paquetes Turísticos')], max_length=20)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.ImageField(upload_to='servicios/')),
            ],
        ),
    ]
