# Generated by Django 5.2.7 on 2025-11-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
