# Generated by Django 5.2.7 on 2025-11-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_imagenservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenservicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios/multi/'),
        ),
    ]
