# Generated by Django 5.2.7 on 2025-11-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_imagenservicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenservicio',
            name='imagen',
            field=models.ImageField(upload_to='servicios/imagenes/'),
        ),
    ]
