# Generated by Django 5.2.7 on 2025-11-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_imagenservicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('auto', 'Automóvil'), ('moto', 'Motocicleta'), ('camioneta', 'Camioneta'), ('camion', 'Camión'), ('autobus', 'Autobús'), ('otro', 'Otro')], help_text='Solo se aplica si la categoría es Vehículo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('vehiculo', 'Renta o Venta de Vehículos'), ('apartamento', 'Renta de Apartamentos'), ('bote', 'Renta de Botes'), ('paquete', 'Paquetes Turísticos')], max_length=20),
        ),
    ]
