# Generated by Django 5.2.7 on 2025-11-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0010_alter_servicio_tipo_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('vehiculo', 'Renta de Vehículos'), ('apartamento', 'Renta de Apartamentos'), ('bote', 'Renta de Botes'), ('paquete', 'Paquetes Turísticos')], max_length=20),
        ),
    ]
