# Generated by Django 5.2.7 on 2025-11-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0011_alter_servicio_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('suv', 'SUV'), ('compacto', 'Compacto'), ('muscle', 'Muscle'), ('sedan', 'Sedan'), ('van', 'Van'), ('electrico', 'Eléctrico'), ('deportivo', 'Deportivo'), ('Hibrido', 'Híbrido'), ('truck', 'Truck'), ('descapotable', 'Descapotable'), ('otro', 'Otro')], help_text='Solo aplica si la categoría es Vehículo', max_length=20, null=True),
        ),
    ]
