# Generated by Django 5.2.7 on 2025-11-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0012_alter_servicio_tipo_vehiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='pregunta_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='pregunta_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='pregunta_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='respuesta_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='respuesta_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='respuesta_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo_es',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='titulo_fr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
