# Generated by Django 5.2.7 on 2025-11-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0013_faq_pregunta_en_faq_pregunta_es_faq_pregunta_fr_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['orden', '-fecha_creacion']},
        ),
        migrations.AddField(
            model_name='servicio',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
