# Generated by Django 5.2.7 on 2025-11-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0014_alter_servicio_options_servicio_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['order', '-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='orden',
            new_name='order',
        ),
    ]
