# Generated by Django 5.2.7 on 2025-11-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0015_alter_servicio_options_rename_orden_servicio_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='servicio',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
