# Generated by Django 5.2.7 on 2025-11-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0016_alter_servicio_options_alter_servicio_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
