# Generated by Django 5.2.7 on 2025-11-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0018_alter_servicio_tipo_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
