# Generated by Django 5.2.7 on 2025-11-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0019_alter_servicio_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenservicio',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='imagenservicio',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[('suv', 'SUV'), ('compacto', 'Compacto'), ('sedan', 'Sedan'), ('exclusive', 'Exclusive'), ('family', 'Family'), ('descapotable', 'Descapotable'), ('otro', 'Otro')], max_length=20, null=True),
        ),
    ]
